package com.igor_shaula.inet_checker.main.utils;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@TypeDoc(createdBy = "Igor Shaula", createdOn = "2017-08-09",
        purpose = "describes an annotation for documenting types" +
                " instead of standard 'Created by ... on ...' generated by Android Studio")
@Documented
//@Inherited - commented to force separate documenting for every possible type's child \
@Retention(RetentionPolicy.SOURCE)
@Target(ElementType.TYPE)

public @interface TypeDoc {

    String noValue = "-";

    String createdBy(); // replaces 'Created by ...' in generated standard javadoc \

    String createdOn(); // replaces 'Created on ...' in generated standard javadoc \

    String purpose(); // required description of the reason for an annotated class creation \

    @SuppressWarnings("unused")
    String modifiedBy() default noValue; // who made functional changes \

    @SuppressWarnings("unused")
    String modifiedOn() default noValue; // when last functional changes were made \

    @SuppressWarnings("unused")
    String comment() default noValue;
}